<?php /** @var \PRostik\ControllerDemo\Block\Demo $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<p><?= $escaper->escapeHtml(__('Full name: %1 %2', $block->getFirstName(), $block->getLastName())) ?></p>
<p> <?= $escaper->escapeHtml(__('Repository URL: ')) ?>
    <a target="_blank"
       href="<?= $escaper->escapeUrl($block->getRepositoryUrl()) ?>"><?= ($block->getRepositoryUrl()) ?></a>
</p>
